name: minimap-app
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: tim/MiniMapApp
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  run_command: npm start
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: 8080 